trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    electron-packager . PFactCalcElectron --overwrite --asar=false --platform=win32 --arch=ia32 --icon=pfactcalc.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"PFactCalcElectron\"
	},
	"author": "Silvio Santoriello",
	"license": "",
	"devDependencies": {
		"electron": "^8.1.1",
		"electron-packager": "^14.2.1"
	}
}

  displayName: "Installa le dipendenze e fa il build dell'app"
