trigger:
- master

pool:
  vmImage: 'win'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm package-win
  displayName: 'npm install and build'
